### ISSUE TITLE
Elastic Search Intialization

### ISSUE THREAD

**Issue by haryoa** [xiaofei05/TSST#1]
Hello, thank you for your wonderful work about style transfer 😄 .

I want to try your implementation, but I need to know how to initialize your Elastic Search index.

Could you tell me the details of how you set up your elastic search's content? What are the properties for both of the datasets?

Thank you in advance :)

**Comment by xiaofei05** [comment]
The following are the properties when creating an index,

```python
# elastic search version: 7.10.1
mappings = {
    "mappings": {
        "properties": {
            "label": {"type": "long"},
            "content": {"type": "text"},
            "id": {"type": "keyword"}
        }
    }
}
```

The `label` field denotes the style of the sentence, corresponding to `LABLE_MAP` in `config.py`. The values of the `id` and `content` fields are the same text sentence, where the `id` field facilitates filtering out the sentences that are the same as the query. Here is an example of Yelp,

```python
{
    '_index': 'yelp',
    '_type': '_doc',
    '_id': 'sY4Et3YBP4apQL1iXe1X',
    '_score': 1.0,
    '_source': {
        'content': "it 's a good toasted hoagie .",
     	'id': "it 's a good toasted hoagie .",
     	'label': 0
    }
}
```

Please feel free to let me know if there are any questions or anything I can help you with. :)

**Comment by haryoa** [comment]
Thank you for the answer!
